run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - ineffassign
    - staticcheck
    - unused
    - govet

#  goimports:
#    local-prefixes: github.com/navantesolutions/apimcore
