version: 2

project_name: apimcore

builds:
  - id: apimcore
    main: ./cmd/apimcore
    binary: apimcore
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64
        goarm: "6"
      - goos: windows
        goarch: arm64
        goarm: "7"

nfpms:
  - id: linux-packages
    package_name: apimcore
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    vendor: Navante Solutions
    homepage: https://github.com/Navante-Solutions/apimCore
    maintainer: Navante Solutions <support@navante.com>
    description: Lightweight, high-performance API gateway with key-based access control, rate limiting, and TUI monitoring.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    ids:
      - apimcore
    dependencies:
      - ca-certificates
    contents:
      - dst: /etc/apimcore
        type: dir
      - dst: /var/lib/apimcore
        type: dir
    overrides:
      deb:
        dependencies:
          - ca-certificates
      rpm:
        dependencies:
          - ca-certificates
